//********************************************************************
//
// INTERESTS Constant
//
// Array of available interest options that users can select for
// their profile. Used in onboarding and profile editing screens.
//
// Return Value
// ------------
// string[]    Array of interest strings
//
//*******************************************************************
export const INTERESTS: string[] = [
  "Photography",
  "Shopping",
  "Karaoke",
  "Yoga",
  "Cooking",
  "Tennis",
  "Running",
  "Swimming",
  "Art",
  "Traveling",
  "Extreme Sports",
  "Music",
  "Drinking",
  "Video Games",
  "Hiking",
  "Gym",
  "Boxing",
  "Coding",
  "Anime",
  "Reading",
  "Beach",
  "Board Games",
  "Cars",
  "Makeup",
  "Fashion",
  "Meditation",
  "Podcasts",
  "Nature",
  "Outdoors",
  "Sports",
  "Basketball",
  "Soccer",
  "Baseball",
  "Volleyball",
  "Golf",
  "Camping",
  "Pets",
  "Dogs",
  "Cats",
  "Cooking Classes",
  "Wine Tasting",
  "Coffee",
  "Craft Beer",
  "Dancing",
  "Singing",
  "Film Photography",
  "Movies",
  "TV Shows",
  "Comics",
  "Sci-fi",
  "Technology",
  "Travel Planning",
  "Road Trips",
  "Thrifting",
  "Interior Design",
  "Foodie",
  "Baking",
  "Fitness",
  "Weightlifting",
  "Skateboarding",
  "Surfing",
  "Snowboarding",
  "Skiing",
  "Chess",
  "Puzzles",
  "DIY Projects",
  "Gardening",
  "Astrology",
  "Spirituality",
  "Volunteering",
  "Business",
  "Investing",
  "Real Estate",
  "Entrepreneurship",
  "Languages",
  "Martial Arts",
  "Collecting",
  "Cars & Motorsports",
  "Cooking New Recipes",
  "Healthy Eating",
  "Pilates",
  "Running Clubs",
];
