//********************************************************************
//
// Photo Utilities
//
// Centralized photo normalization functions to ensure consistent
// handling of profile photos across all components. Prevents
// divergence between SwipeCard, ProfileScreen, and other components.
//
//*******************************************************************

/**
 * Normalizes profile photos array for rendering.
 * Filters out null/undefined/empty strings but trusts backend contract
 * that remaining values are valid image sources (presigned URLs, data URIs, etc.).
 * 
 * Backend Contract: The photos array from API responses contains presigned
 * HTTPS URLs generated by backend/src/profiles/profiles.service.ts::toResponse().
 * AppImage expects these URLs directly - no additional URL resolution needed.
 * 
 * @param photos - Array of photo strings from backend (presigned URLs)
 * @param fallbackUrl - Optional fallback URL (e.g., profileImageUrl)
 * @returns Array of valid photo strings (non-empty, trimmed)
 * 
 * Example:
 *   normalizePhotos(['https://s3...', '', null]) → ['https://s3...']
 *   normalizePhotos([], 'https://fallback') → ['https://fallback']
 *   normalizePhotos([], null) → []
 */
export function normalizePhotos(
  photos: string[] | null | undefined,
  fallbackUrl?: string | null
): string[] {
  // Filter out null/undefined/empty strings (defensive only)
  // Do NOT validate URL format - trust backend contract and let AppImage handle rendering
  const valid = (photos || []).filter(
    (p): p is string => Boolean(p && typeof p === 'string' && p.trim().length > 0)
  );
  
  if (valid.length > 0) {
    return valid;
  }
  
  // Fallback to profileImageUrl if provided (matches backend contract)
  if (fallbackUrl && typeof fallbackUrl === 'string' && fallbackUrl.trim().length > 0) {
    return [fallbackUrl];
  }
  
  return [];
}

